### ISSUE TITLE
building chrome extension

### ISSUE THREAD

**Issue by ajayVibinex** [Alokit-Innovations/chrome-extension#1]
DOD 
- [ ] Figure out events 
- [x] Making UI 
- [x] User Authentication

**Comment by ajayVibinex** [comment]
- Git hub api can be use 
- adding the comments for telling the review coverage through github api 
-

**Comment by avikalpg** [comment]
* UI has been completed (PR yet to be raised)

**Comment by ajayVibinex** [comment]
- ui has been completed 
- UI pr raised and fixed the changes requested 
-

**Comment by ajayVibinex** [comment]
- fixed the css styles for showing important and relevant PR ( PR already raised ) 
- Navbar requested changes completed ( PR already raised ) 
- Working on getting user alias from GITHUB API.

**Comment by ajayVibinex** [comment]
- fixed the changes for removing repeated functions 
- pr raised

**Comment by avikalpg** [comment]
- Bitbucket UI is in progress.
- Chrome extension auth - research is done (found other project builders' answers that do this)

**Comment by ajayVibinex** [comment]
- bitbucket UI is completed, pr raised 
- fix reload issue of extension

**Comment by avikalpg** [comment]
- Facing CORS issue when using NextAuthJS API (this just needs to be solved on the NextJS application end)

**Comment by ajayVibinex** [comment]
- adding repo ui is in progress, a bug needs to be fixed 
- bitbucket Ui is also completed 
- Integrated api 
-

**Comment by avikalpg** [comment]
- [ ] Publish chrome extension on web store
