### ISSUE TITLE
API Integration for showing highlighted files in repo .

### ISSUE THREAD

**Issue by ajayVibinex** [Alokit-Innovations/chrome-extension#15]
DOD 
- [x] Implement API 
- [x] backGround color changes
- [x] encrypt and match

**Comment by ajayVibinex** [comment]
- added api 
- issue while decrypting

**Comment by ajayVibinex** [comment]
- completed above task raised pr 
- avikalp pointed out blunders in pr, doing changes.

**Comment by avikalpg** [comment]
- Bitbucket file highlighting is done
- Setup API calls are pending. Will complete them today.
