### ISSUE TITLE
add loading button while getting data from API

### ISSUE THREAD

**Issue by ajayVibinex** [Alokit-Innovations/chrome-extension#17]
DOD 
- [x] ui for loading 
- [x] implemented for all api loading

**Comment by ajayVibinex** [comment]
- finalized the loading ui, using gif for for now 
-

**Comment by ajayVibinex** [comment]
- added the loading button 
- solving some bugs

**Comment by avikalpg** [comment]
@ajayVibinex I think this ticket is complete, right? I have marked the 2nd task in the description as done, but please verify.
